# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61e779de351a17079b9832068624bfeb00f77e5220990d8cfb83e4c78b8d7509088816e35ff14e827cd8cc7bec5ef56dcd4fc0c4bc063bb7d21ffe03ee30f0e

test:
  secret_key_base: 768345b38ed487e5a51712a9d14dfe90a0b33f78052fad90c3fc89f554e29e3fa8ee0255d1a2100a22a675b762ef5d6cbc5d1bf7b78dbb3e3da37db9a23a3e47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
